# Use official lightweight Python image
FROM python:3.9-slim

# Set working directory inside container
WORKDIR /app

# Copy current directory contents into container at /app
COPY . .

# Install dependencies from requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Specify the port number the app runs on
ENV PORT=8080

# Run the application with gunicorn server binding to the correct port
CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 app:app
